### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [grevelem/TC359project7#1]
One of the few projects I haven't been able to immediately break! While it does work though, I do see some inconsistent indentation in `app.rb` and `index.erb` that I'd like you to fix. The [resources on this page](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) should be helpful here.

Let me know if you encounter any difficulties with that and I'll be happy to hop on a screenshare!

**Comment by grevelem** [comment]
Hi Professor Fritz, I think I got the settings changed in sublime text. Will that automatically update everything to appear is it should or do the new settings apply just to future projects? I guess I'm a little confused on how the code should appear visually. Clarification would be great. Thank you!

**Comment by chrisvfritz** [comment]
The new settings will apply to future files, but to make sure the everything is fixed in current files, [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) has some tips that should help you. Let me know how it goes! :smiley:

**Comment by grevelem** [comment]
Cool I think I got it working correctly, that made things a lot easier! If there are any further changes I should make please let me know. Sorry for the late response and thanks for your time!

**Comment by chrisvfritz** [comment]
That's better, but still not _quite_ right. I have one more tip that should help you finish. If you select all the text in both files (Ctrl+A in Windows or Cmd+A in OS X), then go to `Edit` > `Line` > `Reindent`, any of the imperfections should be fixed and you'll be able to see what's different.

**Comment by grevelem** [comment]
Oh okay! I think I finally got it? Got rid of all that excess tab space

**Comment by chrisvfritz** [comment]
:+1: Beautiful!

**Comment by grevelem** [comment]
Cool! Thanks for your help Professor Fritz! Have a good break!

**Comment by chrisvfritz** [comment]
Not a problem. You as well, hopefully somewhere warm! :smiley:
